# Generated by Django 2.2.1 on 2019-06-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
