# Generated by Django 2.2.1 on 2019-06-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
