# Generated by Django 2.2.1 on 2019-06-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
