# Generated by Django 2.2.1 on 2019-06-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_auto_20190624_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='person',
            name='page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='publication_month',
        ),
        migrations.RemoveField(
            model_name='person',
            name='publication_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_publication',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_publication_month',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_publication_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_volume',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_volume_dump',
        ),
        migrations.RemoveField(
            model_name='person',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='person',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='person',
            name='volume_dump',
        ),
    ]
