# Generated by Django 2.2.1 on 2019-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_auto_20190624_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='middlename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
