# Generated by Django 2.2.1 on 2019-06-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='quaker',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
