# Generated by Django 2.2.1 on 2019-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0009_auto_20190625_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
