# Generated by Django 2.2.1 on 2019-07-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0010_comment_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='middlename',
            new_name='fullname',
        ),
    ]
