# Generated by Django 2.2.1 on 2019-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0011_auto_20190719_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fullname',
            new_name='middlename',
        ),
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='publication_month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='publication_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='publication_year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_publication',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_publication_month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_publication_year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_volume',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_volume_dump',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='volume',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='volume_dump',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
